spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/fitnessdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fitness}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fitness}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

app.jwt.secret=${APP_JWT_SECRET:8m6R1vQyX5hN2kL9pT4cB7dF0gJ3sW8a}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

app.food.seed.enabled=true
app.food.seed.resource=classpath:seed/alimentos.xlsx
app.food.seed.source=TACO
app.food.seed.skip-if-exists=true
