spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/fitnessdb
spring.datasource.username=fitness
spring.datasource.password=fitness

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

app.jwt.secret=8m6R1vQyX5hN2kL9pT4cB7dF0gJ3sW8a
app.jwt.expiration-ms=86400000
